CREATE TABLE IF NOT EXISTS `products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `catégorie` VARCHAR(100) DEFAULT NULL,
  `buyDate` DATE DEFAULT NULL,
  `first_qty` DECIMAL(10,2) DEFAULT 0.00, 
  `qty` DECIMAL(10,2) DEFAULT 0.00,
  `unit` VARCHAR(50) DEFAULT NULL,
  `exp` DATE DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `lastAction` VARCHAR(255) DEFAULT NULL,
  `status` ENUM('0', '1') DEFAULT '1',
  `image` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE products 
MODIFY COLUMN qty DECIMAL(15, 4) NOT NULL DEFAULT '0.0000',
MODIFY COLUMN first_qty DECIMAL(15, 4) NOT NULL DEFAULT '0.0000';


CREATE TABLE IF NOT EXISTS `product_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) NOT NULL,
  `product_name` VARCHAR(255) DEFAULT NULL,
  `catégorie` VARCHAR(100) DEFAULT NULL,
  `buyDate` DATE DEFAULT NULL,
  `qty` DECIMAL(10,2) DEFAULT NULL,
  `unit` VARCHAR(50) DEFAULT NULL,
  `action_type` VARCHAR(50) DEFAULT NULL, 
  `details` TEXT DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `action_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- نزيدو الأصناف اللي عندك دابا كبداية
INSERT IGNORE INTO categories (name) VALUES 
('Alaf / Aliments bétail'), 
('Dwa / Médicaments vétérinaires'), 
('Engrais / Fertilizers'), 
('Semences');